export type Colors =
  | 'concrete'
  | 'white'
  | 'black'
  | 'codgray'
  | 'gray'
  | 'stormDust'
  | 'nero'
  | 'nobel'
  | 'alto'
  | 'dune'
  | 'desertStorm'
  | 'palePurple'
  | 'blueViolet'
  | 'electricPurple'
  | 'veronica'
  | 'steelPink'
  | 'redOrange'
